let

    DataMinima = List.Min(fVendas[Data] & fMetas[Data]),
    AnoMinimo = Date.Year(DataMinima),

    DataMaxima = List.Max(fVendas[Data Envio]), 
    AnoMaximo = Date.Year(DataMaxima),

    Duracao = Duration.Days(#date(AnoMaximo,12,31) - #date(AnoMinimo,1,1)) + 1,

    Fonte = List.Dates(#date(AnoMinimo, 1, 1), Duracao, #duration(1, 0, 0, 0)),
    #"Convertido para Tabela" = Table.FromList(Fonte, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Colunas Renomeadas" = Table.RenameColumns(#"Convertido para Tabela",{{"Column1", "Data"}}),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"Data", type date}}),
    #"Ano Inserido" = Table.AddColumn(#"Tipo Alterado", "Ano", each Date.Year([Data]), Int64.Type),
    #"Nome do Mês Inserido" = Table.AddColumn(#"Ano Inserido", "Nome do Mês", each Date.MonthName([Data]), type text),
    #"Colocar Cada Palavra Em Maiúscula" = Table.TransformColumns(#"Nome do Mês Inserido",{{"Nome do Mês", Text.Proper, type text}}),
    #"Mês Inserido" = Table.AddColumn(#"Colocar Cada Palavra Em Maiúscula", "Mês", each Date.Month([Data]), Int64.Type),
    #"Dia Inserido" = Table.AddColumn(#"Mês Inserido", "Dia", each Date.Day([Data]), Int64.Type),
    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Dia Inserido", "Semestre", each if [Mês] < 6 then "Sem1" else "Sem2"),
    #"Coluna Condicional Adicionada1" = Table.AddColumn(#"Coluna Condicional Adicionada", "Trimestre", each if [Mês] <= 3 then "Tri1" else if [Mês] <= 6 then "Tri2" else if [Mês] <= 9 then "Tri3" else "Tri4"),
    #"Primeiros Caracteres Inseridos" = Table.AddColumn(#"Coluna Condicional Adicionada1", "Mes Abreviado", each Text.Start([Nome do Mês], 3), type text),
    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Primeiros Caracteres Inseridos", "Mes-Ano", each Text.Combine({[Mes Abreviado], "-", Text.From([Ano], "pt-BR")}), type text),
    #"Personalização Adicionada" = Table.AddColumn(#"Coluna Mesclada Inserida", "Mes Ano Classificacao", each [Ano] * 100 + [Mês]),
    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Personalização Adicionada",{{"Mes Ano Classificacao", Int64.Type}, {"Trimestre", type text}, {"Semestre", type text}})
in
    #"Tipo Alterado1"